<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report-3.0.xsd" version="3.0" name="grupo10.messenger.backend.control.ControlTest" time="7.178" tests="21" errors="5" skipped="0" failures="11">
  <properties>
    <property name="java.specification.version" value="23"/>
    <property name="sun.cpu.isalist" value="amd64"/>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.class.path" value="C:\Users\user\Documents\NetBeansProjects\appChatP2P\messenger\target\test-classes;C:\Users\user\Documents\NetBeansProjects\appChatP2P\messenger\target\classes;C:\Users\user\.m2\repository\org\netbeans\external\AbsoluteLayout\RELEASE210\AbsoluteLayout-RELEASE210.jar;C:\Users\user\.m2\repository\org\junit\jupiter\junit-jupiter-api\5.10.3\junit-jupiter-api-5.10.3.jar;C:\Users\user\.m2\repository\org\opentest4j\opentest4j\1.3.0\opentest4j-1.3.0.jar;C:\Users\user\.m2\repository\org\junit\platform\junit-platform-commons\1.10.3\junit-platform-commons-1.10.3.jar;C:\Users\user\.m2\repository\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar;C:\Users\user\.m2\repository\org\junit\jupiter\junit-jupiter-params\5.10.3\junit-jupiter-params-5.10.3.jar;C:\Users\user\.m2\repository\org\junit\jupiter\junit-jupiter-engine\5.10.3\junit-jupiter-engine-5.10.3.jar;C:\Users\user\.m2\repository\org\junit\platform\junit-platform-engine\1.10.3\junit-platform-engine-1.10.3.jar;"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="user.variant" value=""/>
    <property name="java.vendor.url" value="https://java.oracle.com/"/>
    <property name="user.timezone" value="America/Buenos_Aires"/>
    <property name="os.name" value="Windows 10"/>
    <property name="java.vm.specification.version" value="23"/>
    <property name="user.country" value="AR"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.boot.library.path" value="C:\Program Files\Java\jdk-23\bin"/>
    <property name="sun.java.command" value="C:\Users\user\AppData\Local\Temp\surefire9447171882537015551\surefirebooter-20250329205557607_3.jar C:\Users\user\AppData\Local\Temp\surefire9447171882537015551 2025-03-29T20-55-57_485-jvmRun1 surefire-20250329205557607_1tmp surefire_0-20250329205557607_2tmp"/>
    <property name="jdk.debug" value="release"/>
    <property name="surefire.test.class.path" value="C:\Users\user\Documents\NetBeansProjects\appChatP2P\messenger\target\test-classes;C:\Users\user\Documents\NetBeansProjects\appChatP2P\messenger\target\classes;C:\Users\user\.m2\repository\org\netbeans\external\AbsoluteLayout\RELEASE210\AbsoluteLayout-RELEASE210.jar;C:\Users\user\.m2\repository\org\junit\jupiter\junit-jupiter-api\5.10.3\junit-jupiter-api-5.10.3.jar;C:\Users\user\.m2\repository\org\opentest4j\opentest4j\1.3.0\opentest4j-1.3.0.jar;C:\Users\user\.m2\repository\org\junit\platform\junit-platform-commons\1.10.3\junit-platform-commons-1.10.3.jar;C:\Users\user\.m2\repository\org\apiguardian\apiguardian-api\1.1.2\apiguardian-api-1.1.2.jar;C:\Users\user\.m2\repository\org\junit\jupiter\junit-jupiter-params\5.10.3\junit-jupiter-params-5.10.3.jar;C:\Users\user\.m2\repository\org\junit\jupiter\junit-jupiter-engine\5.10.3\junit-jupiter-engine-5.10.3.jar;C:\Users\user\.m2\repository\org\junit\platform\junit-platform-engine\1.10.3\junit-platform-engine-1.10.3.jar;"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="user.home" value="C:\Users\user"/>
    <property name="user.language" value="es"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="java.version.date" value="2024-10-15"/>
    <property name="java.home" value="C:\Program Files\Java\jdk-23"/>
    <property name="file.separator" value="\"/>
    <property name="basedir" value="C:\Users\user\Documents\NetBeansProjects\appChatP2P\messenger"/>
    <property name="java.vm.compressedOopsMode" value="Zero based"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="surefire.real.class.path" value="C:\Users\user\AppData\Local\Temp\surefire9447171882537015551\surefirebooter-20250329205557607_3.jar"/>
    <property name="user.script" value=""/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="java.runtime.version" value="23.0.1+11-39"/>
    <property name="user.name" value="user"/>
    <property name="stdout.encoding" value="Cp1252"/>
    <property name="path.separator" value=";"/>
    <property name="os.version" value="10.0"/>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="maven.ext.class.path" value="C:\Program Files\NetBeans-25\netbeans\java\maven-nblib\netbeans-eventspy.jar"/>
    <property name="localRepository" value="C:\Users\user\.m2\repository"/>
    <property name="java.vendor.url.bug" value="https://bugreport.java.com/bugreport/"/>
    <property name="java.io.tmpdir" value="C:\Users\user\AppData\Local\Temp\"/>
    <property name="java.version" value="23.0.1"/>
    <property name="user.dir" value="C:\Users\user\Documents\NetBeansProjects\appChatP2P\messenger"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="sun.os.patch.level" value=""/>
    <property name="native.encoding" value="Cp1252"/>
    <property name="java.library.path" value="C:\Program Files\Java\jdk-23\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\user\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\user\AppData\Local\Programs\Python\Python312\;C:\Users\user\AppData\Local\Programs\Python\Launcher\;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\user\Desktop\platform-tools;C:\Users\user\AppData\Roaming\npm;C:\ProgramData\user\GitHubDesktop\bin;."/>
    <property name="java.vm.info" value="mixed mode, sharing"/>
    <property name="stderr.encoding" value="Cp1252"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="java.vm.version" value="23.0.1+11-39"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="java.class.version" value="67.0"/>
  </properties>
  <testcase name="testAgregarContacto" classname="grupo10.messenger.backend.control.ControlTest" time="1.017">
    <system-out><![CDATA[Servidor iniciado en el puerto 5000
]]></system-out>
  </testcase>
  <testcase name="testRecibirMensaje_MensajeRedEnOrden" classname="grupo10.messenger.backend.control.ControlTest" time="0.025">
    <error message="Cannot invoke &quot;grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)&quot; because &quot;this.usuario&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)" because "this.usuario" is null
	at grupo10.messenger.backend.control.Control.agregarContacto(Control.java:71)
	at grupo10.messenger.backend.control.ControlTest.testRecibirMensaje_MensajeRedEnOrden(ControlTest.java:403)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></error>
    <system-out><![CDATA[Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:55:59 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testSingletonInstance" classname="grupo10.messenger.backend.control.ControlTest" time="0.003">
    <system-out><![CDATA[Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:55:59 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testEnviarMensajeParametrosInvalidos" classname="grupo10.messenger.backend.control.ControlTest" time="1.02">
    <failure message="Excepción en la prueba: El contenido del mensaje no puede ser nulo o vacío." type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: Excepción en la prueba: El contenido del mensaje no puede ser nulo o vacío.
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at grupo10.messenger.backend.control.ControlTest.testEnviarMensajeParametrosInvalidos(ControlTest.java:244)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></failure>
    <system-out><![CDATA[Servidor no se pudo conectar
Servidor iniciado en el puerto 5002
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:55:59 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testRegistrarParametrosInvalidos" classname="grupo10.messenger.backend.control.ControlTest" time="1.006">
    <failure message="Excepción en la prueba: El nickname no puede ser nulo, vacío o mayor a 16 caracteres." type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: Excepción en la prueba: El nickname no puede ser nulo, vacío o mayor a 16 caracteres.
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at grupo10.messenger.backend.control.ControlTest.testRegistrarParametrosInvalidos(ControlTest.java:84)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></failure>
    <system-out><![CDATA[Servidor no se pudo conectar
Servidor iniciado en el puerto 10000
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:00 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

Exception in thread "Thread-7" java.lang.IllegalArgumentException: Port value out of range: -1
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:270)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:170)
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:34)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Exception in thread "Thread-8" java.lang.IllegalArgumentException: Port value out of range: 70000
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:270)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:170)
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:34)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)
]]></system-err>
  </testcase>
  <testcase name="testAgregarConversacion" classname="grupo10.messenger.backend.control.ControlTest" time="0.002">
    <system-out><![CDATA[Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:01 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testEnviarMensaje_SenderNoTieneContactoNiConversacionReciverNada" classname="grupo10.messenger.backend.control.ControlTest" time="1.012">
    <failure message="Excepción en la prueba: Cannot invoke &quot;grupo10.messenger.backend.modelo.Usuario.getNickname()&quot; because &quot;this.usuario&quot; is null" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: Excepción en la prueba: Cannot invoke "grupo10.messenger.backend.modelo.Usuario.getNickname()" because "this.usuario" is null
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at grupo10.messenger.backend.control.ControlTest.testEnviarMensaje_SenderNoTieneContactoNiConversacionReciverNada(ControlTest.java:289)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></failure>
    <system-out><![CDATA[Servidor no se pudo conectar
Servidor no se pudo conectar
Servidor iniciado en el puerto 5003
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:01 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

mar 29, 2025 8:56:01 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testComunicacionConcurrente" classname="grupo10.messenger.backend.control.ControlTest" time="3.037">
    <failure message="Excepción en la prueba: Cannot invoke &quot;grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)&quot; because &quot;this.usuario&quot; is null" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: Excepción en la prueba: Cannot invoke "grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)" because "this.usuario" is null
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at grupo10.messenger.backend.control.ControlTest.testComunicacionConcurrente(ControlTest.java:518)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></failure>
    <system-out><![CDATA[Servidor no se pudo conectar
Servidor iniciado en el puerto 5001
Servidor no se pudo conectar
Servidor no se pudo conectar
Servidor iniciado en el puerto 5004
Servidor iniciado en el puerto 5005
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:02 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

mar 29, 2025 8:56:03 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

mar 29, 2025 8:56:03 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testRegistrarUsuario" classname="grupo10.messenger.backend.control.ControlTest" time="0.004">
    <failure message="La IP del usuario no coincide ==&gt; expected: &lt;192.168.1.10&gt; but was: &lt;192.168.0.6&gt;" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: La IP del usuario no coincide ==> expected: <192.168.1.10> but was: <192.168.0.6>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1156)
	at grupo10.messenger.backend.control.ControlTest.testRegistrarUsuario(ControlTest.java:51)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></failure>
    <system-out><![CDATA[Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testRecibirMensaje_ContactoExistenteSinConversacion" classname="grupo10.messenger.backend.control.ControlTest" time="0.002">
    <error message="Cannot invoke &quot;grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)&quot; because &quot;this.usuario&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)" because "this.usuario" is null
	at grupo10.messenger.backend.control.Control.agregarContacto(Control.java:71)
	at grupo10.messenger.backend.control.ControlTest.testRecibirMensaje_ContactoExistenteSinConversacion(ControlTest.java:426)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></error>
    <system-out><![CDATA[Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testVerConversacion" classname="grupo10.messenger.backend.control.ControlTest" time="0.002">
    <system-out><![CDATA[Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testEnviarMensaje_SenderTodoReciverContacto" classname="grupo10.messenger.backend.control.ControlTest" time="0.003">
    <failure message="Excepción en la prueba: Cannot invoke &quot;grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)&quot; because &quot;this.usuario&quot; is null" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: Excepción en la prueba: Cannot invoke "grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)" because "this.usuario" is null
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at grupo10.messenger.backend.control.ControlTest.testEnviarMensaje_SenderTodoReciverContacto(ControlTest.java:338)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></failure>
    <system-out><![CDATA[Servidor no se pudo conectar
Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testNoPermitirMismoPuertoEnMultiplesInstancias" classname="grupo10.messenger.backend.control.ControlTest" time="0.003">
    <failure message="La primera instancia debería poder registrarse correctamente. ==&gt; expected: &lt;true&gt; but was: &lt;false&gt;" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: La primera instancia debería poder registrarse correctamente. ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
	at grupo10.messenger.backend.control.ControlTest.testNoPermitirMismoPuertoEnMultiplesInstancias(ControlTest.java:101)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></failure>
    <system-out><![CDATA[Servidor no se pudo conectar
Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testGetUsuario" classname="grupo10.messenger.backend.control.ControlTest" time="0.002">
    <system-out><![CDATA[Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testRecibirMensaje_NullMensajeRed" classname="grupo10.messenger.backend.control.ControlTest" time="0.002">
    <error message="Cannot invoke &quot;grupo10.messenger.backend.modelo.MensajeRed.getContenido()&quot; because &quot;mensaje&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "grupo10.messenger.backend.modelo.MensajeRed.getContenido()" because "mensaje" is null
	at grupo10.messenger.backend.control.Control.recibirMensaje(Control.java:120)
	at grupo10.messenger.backend.control.ControlTest.testRecibirMensaje_NullMensajeRed(ControlTest.java:390)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></error>
    <system-out><![CDATA[Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testAgregarContactoParametrosInvalidos" classname="grupo10.messenger.backend.control.ControlTest" time="0.003">
    <error message="El nickname no puede ser nulo, vacío o mayor a 16 caracteres." type="java.lang.IllegalArgumentException"><![CDATA[java.lang.IllegalArgumentException: El nickname no puede ser nulo, vacío o mayor a 16 caracteres.
	at grupo10.messenger.backend.modelo.Persona.<init>(Persona.java:13)
	at grupo10.messenger.backend.modelo.Contacto.<init>(Contacto.java:7)
	at grupo10.messenger.backend.modelo.Usuario.agregarContacto(Usuario.java:27)
	at grupo10.messenger.backend.control.Control.agregarContacto(Control.java:71)
	at grupo10.messenger.backend.control.ControlTest.testAgregarContactoParametrosInvalidos(ControlTest.java:129)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></error>
    <system-out><![CDATA[Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testEnviarMensaje_SenderTieneContactoNoConversacionReciverNada" classname="grupo10.messenger.backend.control.ControlTest" time="0.003">
    <failure message="Excepción en la prueba: Cannot invoke &quot;grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)&quot; because &quot;this.usuario&quot; is null" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: Excepción en la prueba: Cannot invoke "grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)" because "this.usuario" is null
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at grupo10.messenger.backend.control.ControlTest.testEnviarMensaje_SenderTieneContactoNoConversacionReciverNada(ControlTest.java:267)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></failure>
    <system-out><![CDATA[Servidor no se pudo conectar
Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testRecibirMensaje_SinContactoNiConversacion" classname="grupo10.messenger.backend.control.ControlTest" time="0.003">
    <error message="Cannot invoke &quot;grupo10.messenger.backend.modelo.Usuario.buscarConversacion(String, int)&quot; because &quot;this.usuario&quot; is null" type="java.lang.NullPointerException"><![CDATA[java.lang.NullPointerException: Cannot invoke "grupo10.messenger.backend.modelo.Usuario.buscarConversacion(String, int)" because "this.usuario" is null
	at grupo10.messenger.backend.control.Control.recibirMensaje(Control.java:121)
	at grupo10.messenger.backend.control.ControlTest.testRecibirMensaje_SinContactoNiConversacion(ControlTest.java:448)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></error>
    <system-out><![CDATA[Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testVerConversacionParametrosInvalidos" classname="grupo10.messenger.backend.control.ControlTest" time="0.004">
    <failure message="La conversación debería existir. ==&gt; expected: not &lt;null&gt;" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: La conversación debería existir. ==> expected: not <null>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:49)
	at org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:35)
	at org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:312)
	at grupo10.messenger.backend.control.ControlTest.testVerConversacionParametrosInvalidos(ControlTest.java:170)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></failure>
    <system-out><![CDATA[Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testEnviarMensaje_SenderTodoReciverNada" classname="grupo10.messenger.backend.control.ControlTest" time="0.004">
    <failure message="Excepción en la prueba: Cannot invoke &quot;grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)&quot; because &quot;this.usuario&quot; is null" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: Excepción en la prueba: Cannot invoke "grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)" because "this.usuario" is null
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at grupo10.messenger.backend.control.ControlTest.testEnviarMensaje_SenderTodoReciverNada(ControlTest.java:313)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></failure>
    <system-out><![CDATA[Servidor no se pudo conectar
Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
  <testcase name="testEnviarMensaje_SenderTodoReciverTodo" classname="grupo10.messenger.backend.control.ControlTest" time="0.003">
    <failure message="Excepción en la prueba: Cannot invoke &quot;grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)&quot; because &quot;this.usuario&quot; is null" type="org.opentest4j.AssertionFailedError"><![CDATA[org.opentest4j.AssertionFailedError: Excepción en la prueba: Cannot invoke "grupo10.messenger.backend.modelo.Usuario.agregarContacto(String, String, int)" because "this.usuario" is null
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at grupo10.messenger.backend.control.ControlTest.testEnviarMensaje_SenderTodoReciverTodo(ControlTest.java:377)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
]]></failure>
    <system-out><![CDATA[Servidor no se pudo conectar
Servidor no se pudo conectar
]]></system-out>
    <system-err><![CDATA[mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

mar 29, 2025 8:56:05 P. M. grupo10.messenger.backend.red.Server run
SEVERE: null
java.io.IOException: No se puedo generar conexion con el puerto desde el servidor
	at grupo10.messenger.backend.red.Server.iniciarServidor(Server.java:48)
	at grupo10.messenger.backend.red.Server.run(Server.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1575)

]]></system-err>
  </testcase>
</testsuite>